CREATE TABLE public.User (
    ID SERIAL,
    NAME VARCHAR(200) NOT NULL,
    LOGIN VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT now(),
    PRIMARY KEY (ID)
);